version: 2.1
orbs:
  android: circleci/android@2.4.0
  codecov: codecov/codecov@4.0.1

# Workflows orchestrate a set of jobs to be run;
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - validate-code
      - build-and-unit-test:
          requires:
            - validate-code
      # - functional-test:
      #     requires:
      #       - validate-code
 
jobs:
  validate-code:
    executor:
      name: android/android-docker
      resource-class: medium
      tag: 2024.01.1

    steps:
      - checkout

      - android/restore-gradle-cache

      - android/restore-build-cache

      - run:
          name: Check Format
          command: make checkformat

      - run:
          name: Check Style
          command: make checkstyle

      - android/save-gradle-cache

      - android/save-build-cache

      - store_artifacts:
          path: code/places/build/reports     
  build-and-unit-test:
    executor:
      name: android/android-docker
      resource-class: medium
      tag: 2024.01.1
 
    steps:
      - checkout

      - android/restore-gradle-cache
       
      - android/restore-build-cache

      - run:
          name: Javadoc
          command: make javadoc

      - store_artifacts:
          path: code/messaging/build/docs/javadoc

      - run:
          name: Assemble Phone
          command: make assemble-phone
          
      - run:
          name: Assemble App
          command: make assemble-app

      - android/run-tests:
          test-command: make unit-test-coverage

      - store_artifacts:
          path: code/messaging/build/reports/tests

      - store_test_results:
          path: code/messaging/build/test-results/testPhoneDebugUnitTest

      - android/save-gradle-cache

      - android/save-build-cache

      - codecov/upload:
          file: code/messaging/build/reports/coverage/test/phone/debug/report.xml
          flags: unit-tests
  functional-test:
    executor: 
      name: android/android-machine
      resource-class: large
      tag: 2024.01.1

    steps:
      - checkout

      - android/restore-build-cache

      - run:
          name: List available emulator images
          command: sdkmanager --list

      - android/start-emulator-and-run-tests:
          #   It should match the name seen in the "sdkmanager --list" output
          system-image: system-images;android-29;default;x86
          #   The command to be run, while waiting for emulator startup
          post-emulator-launch-assemble-command: make assemble-phone
          #   The test command
          test-command: make functional-test-coverage
   
      - android/save-build-cache

      - codecov/upload:
          file: code/messaging/build/reports/coverage/androidTest/phone/debug/connected/report.xml
          flags: functional-tests
 
      - store_artifacts:
          path: code/messaging/build/reports/androidTests

      - store_test_results:
          path: code/messaging/build/outputs/androidTest-results
